FROM golang:1.18.9

# Define la ruta de trabajo dentro del contenedor
WORKDIR /go1.18/cdg/helloworld/src/app
COPY . .

# No necesitas copiar ninguna aplicación, ya que no tienes ninguna
RUN go build -o hello_world